site_metadata:
  title: "tropixel quantumfagia"
  description: "Só perguntando."
  # Available themes: architect, cayman, dinky, hacker, leap-day, merlot, midnight, minima, minimal, modernist, slate, tactile, time-machine
  theme: "minima"
  github_repository_url: "git@github.com:tropixelorg/quantumfagia.git" #edit this line
  github_pages_url: "https://tropixelorg.github.io/quantumfagia/" #edit this line
  custom_domain: "quantumfagia.tropixel.org" # Add your custom domain here, or leave as '<none>'

source_repository: "https://github.com/fonte-wiki/Backup-fonte-wiki" #leave this to use fonte.wiki as the source repository

content_mapping:
  home_page_source: "projetos/tqf.md" #edit this line to choose the home page of your website
  subpages_folder: "projetos/quantumfagia" #optionally add a folder from the source repository whose contents will be imported as subpages
  destination_folder: "site_contents"
  media_destination_folder: "assets/media"
